### ISSUE TITLE
Danger Zone Compatibility

### ISSUE THREAD

**Issue by ravingdragoon** [ironmonk88/monks-scene-navigation#23]
The module does not appear to allow Danger Zone buttons to appear in the folders drop down at the top of the screen, making it impossible to use the module for manually activated dangers.

**Comment by napolitanod** [comment]
Thank you - I saw this on my Danger Zone repo also. Let me first take a look to see if I can find a home for the Danger Zone buttons if MSN scene nav is enabled. Essentially it appears like the navigation id is being suppressed by MSN, probably because it is being hidden in place of the custom presentation, and I see that there's possibly a forced spacing with the scene names in the nav bar in this module which will mess with the buttons (my guess, I may be wrong on some/all of my reading of MSN code). 

I likely can just present the buttons beneath the full navigation.

Will be in touch!

**Comment by ironmonk88** [comment]
Closing this as I think it was handled in Danger Zone.
